# Generated by Django 5.2.4 on 2025-07-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='next_available_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
