# Generated by Django 5.2.4 on 2025-08-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rentalitem_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='rent_per_day',
            field=models.IntegerField(default=0),
        ),
    ]
