# Generated by Django 5.2.4 on 2025-08-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rentalitem_rent_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='is_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
