# Generated by Django 5.2.4 on 2025-08-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rentalrequest_is_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='is_overdue_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
