# Generated by Django 5.2.4 on 2025-08-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrequest',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='city',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='aadhar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
