# Generated by Django 5.2.4 on 2025-08-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_rentalrequest_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
