# Generated by Django 5.2.4 on 2025-08-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
