# Generated by Django 5.2.4 on 2025-08-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rentalrequest_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
