# Generated by Django 5.2.4 on 2025-08-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_rentalrequest_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
