# Generated by Django 5.2.4 on 2025-08-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rentalrequest_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='TEMP12345', max_length=100),
            preserve_default=False,
        ),
    ]
