# Generated by Django 5.2.4 on 2025-08-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_payment_order_id_alter_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
