# Generated by Django 5.2.4 on 2025-08-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_payment_order_id_alter_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Security deposit amount set by admin', max_digits=10),
        ),
    ]
