# Generated by Django 5.2.4 on 2025-08-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rentalitem_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
