# Generated by Django 5.2.4 on 2025-08-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_payment_razorpay_order_id_alter_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
