# Generated by Django 5.2.4 on 2025-08-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
